name: hello-world

on: pull_request_target

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: new step
        run: echo hello
      - name: my-step
        run: echo ${{ secrets.secret }}